### ISSUE TITLE
Fix errors in optionsMenu.js

### ISSUE THREAD

**Issue by CharlieS1103** [CharlieS1103/spicetify-marketplace#90]
(The vscode type errors)

**Comment by theRealPadster** [comment]
I think most of them are TypeScript complaining because we didn't specify a component type for the memo function, so it's only expecting the base React `children` prop. I'm not sure if it's possible to do that with comments, or it would need to be actual typescript to get rid of the error, since we'd have to add the `<type>` to it, which is invalid JS. We may need to just `//@ts-ignore` them. 

![image](https://user-images.githubusercontent.com/1565883/152667592-42603982-b3ff-4619-8fa3-3aa4726f18ae.png)
