### ISSUE TITLE
Icon and whole marketplace not showing

### ISSUE THREAD

**Issue by spati-hub** [CharlieS1103/spicetify-marketplace#91]
Title explains it all I think, I also tried without any theme and with different themes I'm on the newest version of Spotify and Spicetify
![image](https://user-images.githubusercontent.com/73031269/147607939-f7cd2c8d-ffb3-4a58-82a1-e4b2e4381646.png)

**Comment by CharlieS1103** [comment]
@spati-hub Mind sending your config file, this seems more like a spicetify issue than a marketplace one

**Comment by spati-hub** [comment]
[config - Copy.txt](https://github.com/CharlieS1103/spicetify-marketplace/files/7796397/config.-.Copy.txt)
I made it a txt so i can upload

**Comment by CharlieS1103** [comment]
@spati-hub For starters, it's a good idea to remove the dribblishdynamic extension if you plan on using marketplace to install themes. Also, would you mind sending me a screenshot of the contents of the CustomApps folder??

**Comment by CharlieS1103** [comment]
@spati-hub I recommend removing the marketplace download you installed and instead using one of our download commands found in the readme! If that does fix the issue just mention me in this issue.

**Comment by spati-hub** [comment]
Sorry for not answering, I already had it installed with the command.

**Comment by Otsumugi** [comment]
i am currently having the same issue however every time I reinstall the marketplace addon, it saves the theme I had with it before and goes blank all over again instead of starting off fresh. I don't know how to fix this but I cant do anything cause it's all blank lol. 
![Capture](https://user-images.githubusercontent.com/100044151/154815358-d3cd6429-8682-42a8-90c8-81cb54e6569d.PNG)

**Comment by CharlieS1103** [comment]
@Otsumugi This is a spicetify issue, run ``spicetify upgrade`` then rerun the marketplace install command.
